---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: demo
  namespace: dev
spec:
  chart:
    git: https://github.com/steven-sheehy/fluxcd-demo.git
    path: chart/fluxcd-demo
    ref: d4ff0a65c3c8b2b33d70925e40674b2fb6c96f42
  rollback:
    enable: true
    force: true
    timeout: 500
    wait: true
  timeout: 500
  wait: true
  values:
    demo-child:
      image:
        tag: master-d4ff0a65c3c8b2b33d70925e40674b2fb6c96f42
    image:
      repository: ssheehy/fluxcd-demo
      tag: master-d4ff0a65c3c8b2b33d70925e40674b2fb6c96f42
