---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: demo
  namespace: dev
spec:
  chart:
    git: https://github.com/steven-sheehy/fluxcd-demo.git
    path: chart/fluxcd-demo
    ref: 728a92d4841177368ced5e4452fecd42e0d357ed
  releaseName: fluxcd
  rollback:
    enable: true
    force: true
    timeout: 500
    wait: true
  timeout: 500
  wait: true
  values:
    image:
      repository: ssheehy/fluxcd-demo
      tag: master-728a92d4841177368ced5e4452fecd42e0d357ed
