---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: demo
  namespace: dev
spec:
  chart:
    git: https://github.com/steven-sheehy/fluxcd-demo.git
    path: chart/fluxcd-demo
    ref: 73955feb30ddbda1d93ff492439fe26d4580cc6d
  releaseName: fluxcd
  rollback:
    enable: true
    force: true
    timeout: 500
    wait: true
  timeout: 500
  wait: true
  values:
    image:
      repository: ssheehy/fluxcd-demo
      tag: master-73955feb30ddbda1d93ff492439fe26d4580cc6d
