---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: demo
  namespace: dev
spec:
  chart:
    git: https://github.com/steven-sheehy/fluxcd-demo.git
    path: chart/fluxcd-demo
    ref: a8db0337d7d81de89fca5f86a898805a48f658fa
  rollback:
    enable: true
    force: true
    timeout: 500
    wait: true
  timeout: 500
  wait: true
  values:
    demo-child:
      image:
        tag: master-a8db0337d7d81de89fca5f86a898805a48f658fa
    image:
      repository: ssheehy/fluxcd-demo
      tag: master-a8db0337d7d81de89fca5f86a898805a48f658fa
