---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: demo
  namespace: dev
spec:
  chart:
    git: https://github.com/steven-sheehy/fluxcd-demo.git
    path: chart/fluxcd-demo
    ref: 343084bb00fdc74cd8b1a9776e0c19cb4a6bf03e
  releaseName: fluxcd
  rollback:
    enable: true
    force: true
    timeout: 500
    wait: true
  timeout: 500
  wait: true
  values:
    image:
      repository: ssheehy/fluxcd-demo
      tag: master-343084bb00fdc74cd8b1a9776e0c19cb4a6bf03e
