---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: demo
  namespace: dev
spec:
  chart:
    git: https://github.com/steven-sheehy/fluxcd-demo.git
    path: chart/fluxcd-demo
    ref: 80e7be5f400b34abcb90712d6d8dcd5c6739872f
  forceUpgrade: true
  releaseName: fluxcd
  resetValues: true
  rollback:
    enable: true
    force: true
    timeout: 500
    wait: true
  timeout: 500
  wait: true
  values:
    image:
      repository: ssheehy/fluxcd-demo
      tag: master-80e7be5f400b34abcb90712d6d8dcd5c6739872f
